tech_agg = {
    "coal_pre2025": "Fossil fuel solid",
    "coal_ccs_pre2025": "Fossil fuel solid",
    "coal_retire_pre2025": "Fossil fuel solid",
    "diesel_pre2025": "Fossil fuel liquid",
    "diesel_bio_pre2025": "Fossil fuel liquid",
    "diesel_backup_pre2025": "Fossil fuel liquid",
    "diesel_bio_post2025": "Fossil fuel liquid",
    "diesel_backup_post2025": "Fossil fuel liquid",
    "hydro_daily": "Hydro",
    "hydro_monthly": "Hydro",
    "hydro_run": "Hydro",
    "h2blue_CT": "Hydrogen - blue",
    "h2blue_ct": "Hydrogen - blue",
    "h2green_CT": "Hydrogen - green",
    "h2green_ct": "Hydrogen - green",
    "gasSC_pre2025": "Fossil fuel gas",
    "gassc_pre2025": "Fossil fuel gas",
    "gassc_ccs_pre2025": "Fossil fuel gas",
    "gasSC_rng_pre2025": "Fossil fuel gas",
    "gassc_rng_pre2025": "Fossil fuel gas",
    "gassc_backup_pre2025": "Fossil fuel gas",
    "gasSC_rng_post2025": "Fossil fuel gas",
    "gassc_rng_post2025": "Fossil fuel gas",
    "gasSC_backup_post2025": "Fossil fuel gas",
    "gassc_backup_post2025": "Fossil fuel gas",
    "gasCCS_post2025": "Fossil fuel gas",
    "gasccs_post2025": "Fossil fuel gas",
    "gasCC_pre2025": "Fossil fuel gas",
    "gascc_pre2025": "Fossil fuel gas",
    "gascc_ccs_pre2025": "Fossil fuel gas",
    "gasCC_rng_pre2025": "Fossil fuel gas",
    "gascc_rng_pre2025": "Fossil fuel gas",
    "gascc_backup_pre2025": "Fossil fuel gas",
    "gasCC_rng_post2025": "Fossil fuel gas",
    "gascc_rng_post2025": "Fossil fuel gas",
    "gascc_backup_post2025": "Fossil fuel gas",
    "gasCC_backup_post2025": "Fossil fuel gas",
    "nuclear_SMR": "Nuclear",
    "nuclear_smr": "Nuclear",
    "storage_PH": "PH Storage",
    "storage_LI": "LI Storage",
    "wind_ons": "Wind",
    "wind_ofs": "Wind",
    "storage_ph": "PH Storage",
    "storage_li": "LI Storage",
    "biomass": "Biomass",
    "Wind_ons": "Wind",
    "Wind_ofs": "Wind",
    "Wind_ons_Recon": "Wind",
    "Wind_ofs_Recon": "Wind",
    "FixedOM Wind_ons": "Wind",
    "FixedOM Wind_ofs": "Wind",
    'wind_ofs_recon':"Wind", 
    'wind_ons_recon': "Wind",
    'solar_recon': "Solar",
    "solar": "Solar",
    "Solar": "Solar",
    "Solar_Recon": "Solar",
    "FixedOM Solar": "Solar",
    "Hydro Capital Cost": "Hydro",
    "ROR Hydro Renewal": "Hydro",
    "Day Hydro Renewal": "Hydro",
    "Month Hydro Renewal": "Hydro",
    "ROR Hydro Capacity": "Hydro",
    "Day Hydro Capacity": "Hydro",
    "Month Hydro Capacity": "Hydro",
    "ROR Hydro Out": "Hydro",
    "Day Hydro Out": "Hydro",
    "Month Hydro Out": "Hydro",
    "New Storage Capacity": "Storage",
    "coal_fuelblending_pre2025": "Fossil fuel solid",
    "coal_backup_pre2025": "Fossil fuel solid",
    "diesel_fuelblending_pre2025": "Fossil fuel liquid",
    "diesel_ccs_pre2025": "Fossil fuel liquid",
    "diesel_retire_pre2025": "Fossil fuel liquid",
    "gasSC_fuelblending_pre2025": "Fossil fuel gas",
    "gasSC_ccs_pre2025": "Fossil fuel gas",
    "gasSC_backup_pre2025": "Fossil fuel gas",
    "gasSC_retire_pre2025": "Fossil fuel gas - retired",
    "gasCC_fuelblending_pre2025": "Fossil fuel gas",
    "gasCC_ccs_pre2025": "Fossil fuel gas",
    "gasCC_backup_pre2025": "Fossil fuel gas",
    "gasCC_retire_pre2025": "Fossil fuel gas - retired",
    "nuclear": "Nuclear",
    "Fixed_OM.biomass": "Biomass",
    "Fixed_OM.h2blue_CT": "Hydrogen",
    "Fixed_OM.h2green_CT": "Hydrogen",
    "Fixed_OM.coal_fuelblending_pre2025": "Fossil fuel solid",
    "Fixed_OM.coal_backup_pre2025": "Fossil fuel solid",
    "Fixed_OM.coal_retire_pre2025": "Fossil fuel solid",
    "Fixed_OM.diesel_fuelblending_pre2025": "Fossil fuel liquid",
    "Fixed_OM.diesel_ccs_pre2025": "Fossil fuel liquid",
    "Fixed_OM.diesel_backup_pre2025": "Fossil fuel liquid",
    "Fixed_OM.diesel_retire_pre2025": "Fossil fuel liquid",
    "Fixed_OM.gasSC_fuelblending_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasSC_ccs_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasSC_backup_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasSC_retire_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasCCS_post2025": "Fossil fuel gas",
    "Fixed_OM.gasCC_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasCC_fuelblending_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasCC_ccs_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasCC_backup_pre2025": "Fossil fuel gas",
    "Fixed_OM.gasCC_retire_pre2025": "Fossil fuel gas",
    "Fixed_OM.nuclear": "Nuclear",
    "Fixed_OM.nuclear_SMR": "Nuclear",
    "Fixed_OM.diesel_bio_pre2025": "Fossil fuel liquid",
    "Fixed_OM.diesel_bio_post2025": "Fossil fuel liquid",
    'Fixed_OM.diesel_backup_post2025': "Fossil fuel liquid",
    'Fixed_OM.gasSC_rng_pre2025': "Fossil fuel gas",
    'Fixed_OM.gasSC_rng_post2025': "Fossil fuel gas",
    'Fixed_OM.gasSC_backup_post2025': "Fossil fuel gas",
    'Fixed_OM.gasCC_rng_pre2025': "Fossil fuel gas",
    'Fixed_OM.gasCC_rng_post2025': "Fossil fuel gas",
    'Fixed_OM.gasCC_backup_post2025': "Fossil fuel gas",
    "Variable_OM.biomass": "Biomass",
    "Variable_OM.h2blue_CT": "Hydrogen",
    "Variable_OM.h2green_CT": "Hydrogen",
    "Variable_OM.coal_fuelblending_pre2025": "Fossil fuel solid",
    "Variable_OM.coal_backup_pre2025": "Fossil fuel solid",
    "Variable_OM.coal_retire_pre2025": "Fossil fuel solid",
    "Variable_OM.diesel_fuelblending_pre2025": "Fossil fuel liquid",
    "Variable_OM.diesel_ccs_pre2025": "Fossil fuel liquid",
    "Variable_OM.diesel_backup_pre2025": "Fossil fuel liquid",
    "Variable_OM.diesel_retire_pre2025": "Fossil fuel liquid",
    "Variable_OM.gasSC_fuelblending_pre2025": "Fossil fuel gas",
    "Variable_OM.gasSC_backup_pre2025": "Fossil fuel gas",
    "Variable_OM.gasSC_retire_pre2025": "Fossil fuel gas",
    "Variable_OM.gasCCS_post2025": "Fossil fuel gas",
    "Variable_OM.gasCC_pre2025": "Fossil fuel gas",
    "Variable_OM.gasCC_fuelblending_pre2025": "Fossil fuel gas",
    "Variable_OM.gasCC_ccs_pre2025": "Fossil fuel gas",
    "Variable_OM.gasCC_backup_pre2025": "Fossil fuel gas",
    "Variable_OM.gasCC_retire_pre2025": "Fossil fuel gas",
    "Variable_OM.nuclear": "Nuclear",
    "Variable_OM.nuclear_SMR": "Nuclear",
    "Variable_OM.diesel_bio_pre2025": "Fossil fuel liquid",
    "Variable_OM.diesel_bio_post2025": "Fossil fuel liquid",
    'Variable_OM.diesel_backup_post2025': "Fossil fuel liquid",
    'Variable_OM.gasSC_rng_pre2025': "Fossil fuel gas",
    'Variable_OM.gasSC_rng_post2025': "Fossil fuel gas",
    'Variable_OM.gasSC_backup_post2025': "Fossil fuel gas",
    'Variable_OM.gasCC_rng_pre2025': "Fossil fuel gas",
    'Variable_OM.gasCC_rng_post2025': "Fossil fuel gas",
    'Variable_OM.gasCC_backup_post2025': "Fossil fuel gas",
    "windofs": "Wind",
    "windons": "Wind",
    "daystoragehydro": "Hydro",
    "monthstoragehydro": "Hydro",
    'gasCG_free_pre2025': "Fossil fuel gas",
    'gasCG_free_retire_pre2025': "Fossil fuel gas - retired",
    'gasCG_restricted_pre2025': "Fossil fuel gas",
    'gasCG_restricted_ccs_pre2025': "Fossil fuel gas",
    'gasCG_restricted_rng_pre2025': "Fossil fuel gas",
    'gasCG_restricted_backup_pre2025': "Fossil fuel gas",
    'gasCG_restricted_retire_pre2025': "Fossil fuel gas - retired",
    'gasCC_free_post2025': "Fossil fuel gas",
    'gascg_free_pre2025': "Fossil fuel gas",
    'gascc_free_pre2025': "Fossil fuel gas",
    'gascc_free_post2025': "Fossil fuel gas",
    'gascg_free_post2025': "Fossil fuel gas",
}

# idea colors:
# idea_colors = {
#     "solar":"#FFFF99",
#     "storage_PH": "#6A3D9A",
#     "storage_LI": "#B39DE3",
#     "wind_ons": "#B2DF8A",
#     "wind_ofs": "#B2DF8A",
#     "nuclear": "#FF7F00",
#     "gas": "#FF6B6B",
#     "hydro": "#A6CEE3",
#     "h2blue": "#8B98E3",
#     "gas_retire": "#784315",
#     "gas_backup": "#FF6B6B",
#     "Solar":"#FFFF99",
#     "storage_PH": "#6A3D9A",
#     "storage_LI": "#B39DE3",
#     "Wind": "#B2DF8A",
#     "nuclear": "#FF7F00",
#     "Fossil fuel gas": "#FF6B6B",
#     "hydro": "#A6CEE3",
#     "h2blue": "#8B98E3",
#     "gas_retire": "#784315",
#     "gas_backup": "#FF6B6B",
# }

IDEA_COLORS = {
        "Fossil fuel gas": "#ff6b6b",
        "Fossil fuel gas - retired": "#784315", 
        "Fossil fuel gas CCS": "#ffaaa3",
        "Fossil fuel gas backup": "#ffcbc5",
        "Fossil fuel liquid": "#ffaa33",
        "Fossil fuel liquid bio": "#ffcc66",
        "Fossil fuel liquid backup": "#ffe5a7",
        "Fossil fuel solid": "#b15928",
        "Fossil fuel solid CCS": "#8b4513",
        'Hydro': '#a6cee3',
        'Hydrogen - green': '#2de35e',
        'Hydrogen - blue': '#2496e3',
        'PH Storage': '#6a3d9a',
        'LI Storage': '#B39DE3',
        'Wind': '#b2df8a',
        'biomass': '#33a02c',
        'Biomass': '#33a02c',
        'nuclear': '#ff7f00',
        'Nuclear': '#ff7f00',
        'solar': '#ffff99',
        'Solar': '#ffff99',
        'DR': '#b8860b',
        'Other': '#d9a670',
        'Under 25 MW': '#cab2d6',
        'Imports': '#666666',
        'Imports from USA': '#666666',
        'Capacity Imports': '#666666',
        'Exports': '#b3b4b2',
        'Exports to USA': '#b3b4b2',
        'Capacity Exports': '#b3b4b2',
        'RNG': '#1f78b4',
        'Total': '#000000'
    }